### PR TITLE
upgrade http-hash@2

### PR DESCRIPTION
**Pull request by wenbing**

### CODE REVIEW

**Comment by michaelnisi** [comment]
What is blocking this?

**Comment by michaelnisi** [comment]
OK, cleared! I think I get it—using `http-hash` directly now, which also gives me more flexibility with my routes. Thanks for these nice packages: `http-hash` and `http-methods`.

**Comment by bcomnes** [comment]
I merged this on a fork https://github.com/bcomnes/http-hash-router/ although I'm happy to lend a maintainence hand if you want @Matt-Esch .

**Comment by Matt-Esch** [comment]
This has been updated (major version bump v2), but I do prefer to use http-hash directly personally.

**Pull request closed without merging**
